Qfxcinema/api/urls.py
from django.urls import path, include
from .views import MovieViewSet, GenreViewSet
from rest_framework.routers import DefaultRouter


router  = DefaultRouter()
router.register(r'genres', GenreViewSet)
router.register(r'movies', MovieViewSet)


urlpatterns = [

	path('', include(router.urls)),
	path('api-auth', include('rest_framework.urls', namespace='rest_framework'))
]

Qfxcinema/urls.py
from django.urls import path, include
from .movie_views import MovieListView, MovieDetailView, MovieCreateView, MovieUpdateView, movie_search, rating_create, MovieDeleteView
from .genre_views import GenreListView, GenreDetailView, GenreCreateView, GenreUpdateView, genre_search
from Qfxcinema.user_views import UserRegisterView, UserProfileView
from .tag_views import TagListView, TagDetailView, TagCreateView, TagUpdateView, tag_search
from .language_views import LanguageCreateView, LanguageListView, LanguageUpdateView, LanguageDeleteView
from django.contrib.auth.views import LoginView, LogoutView
from django.views.generic import TemplateView

app_name = 'Qfxcinema'

urlpatterns = [

    path('', MovieListView.as_view(), name='movie-list'),
    path('search/', movie_search, name='movie_search'),
    path('create/', MovieCreateView.as_view(), name='movie-create'),
    path('<int:pk>/', MovieDetailView.as_view(), name='movie-detail'),
    path('<int:pk>/update/', MovieUpdateView.as_view(), name='movie-update'),
    path('<int:pk>/delete/', MovieDeleteView.as_view(), name='movie-delete'),

    path('', GenreListView.as_view(), name='genre-list'),
    path('genre/search/', genre_search, name='genre_search'),
    path('create/genre/', GenreCreateView.as_view(), name='genre-create'),
    path('genre/<int:pk>/', GenreDetailView.as_view(), name='genre-detail'),
    path('genre/<int:pk>/update/', GenreUpdateView.as_view(), name='genre-update'),

    path('', TagListView.as_view(), name='tag-list'),
    path('search/', genre_search, name='tag_search'),
    path('create/tag/', TagCreateView.as_view(), name='tag-create'),
    path('<int:pk>/', TagDetailView.as_view(), name='tag-detail'),
    path('tag/<int:pk>/update/', TagUpdateView.as_view(), name='tag-update'),

    path('user/register/', UserRegisterView.as_view(), name='user_register'),
    path('user/profile/', UserProfileView.as_view(), name='user-detail'),
    path('user/login/', LoginView.as_view(template_name='user/login.html'), name='login'),
    path('user/logout/', LogoutView.as_view(next_page='/movie'), name='logout'),



    path('language/create/', LanguageCreateView.as_view(), name='language-create'),
    path('language/list/', LanguageListView.as_view(), name='language-list'),
    path('language/<int:pk>/update/', LanguageUpdateView.as_view(), name='language-update'),
    path('language/<int:pk>/delete/', LanguageDeleteView.as_view(), name='language-delete'),

    path('rating/create/', rating_create, name='movie_rating')
]

cinemasite/urls.py
from django.contrib import admin
from django.urls import path, include
from . import settings
from django.conf.urls.static import static


urlpatterns = [
    path('admin/', admin.site.urls),
    path('movie/', include('Qfxcinema.urls')),
    path('api/', include('Qfxcinema.api.urls')),


]



if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

Qfxcinema/models.py
from django.db import models
from django.urls import reverse
from django.utils.text import slugify
from django.contrib.auth.models import User
from django.dispatch import receiver
from django.db.models.signals import post_save


class Genre(models.Model):
    name = models.CharField(max_length=30)


    def __str__(self):
        return self.name


class Movie(models.Model):
    name = models.CharField(max_length=100, blank=False, null=False)
    genre = models.ForeignKey(Genre, related_name='genre', on_delete=models.DO_NOTHING)
    release_date = models.DateField(auto_now=False, auto_now_add=False)
    run_time = models.CharField(max_length=15)
    cast = models.TextField()
    slug = models.SlugField(unique=True, blank=True, max_length=50, null=True)
    poster = models.ImageField(upload_to='posters', null=True)
    youtube_link = models.TextField(blank=True, null=True)

    def __str__(self):
        return self.name

    def Moviesave(self):
        self.slug = slugify(self.name)
        super(Movie).save(Movie)

    def get_absolute_url(self):
        return reverse('Qfxcinema:movie-list')


    @property
    def get_user_rating(self):
        movie_object = Movie.objects.get(pk=self.pk)
        user_ratings_dict = movie_object.ratedmovie.all().values('user__username', 'rating')
        user_ratings_list = []
        user_ratings = ''
        for item in user_ratings_dict:
            user_ratings += '<li>' + item['user__username'] + ' has give rating of ' + \
                            str(item['rating']) + '</li>'
            user_ratings_list = user_ratings
        return user_ratings_list

    def star_percentage(self, rating):
        movie_object = Movie.objects.get(pk=self.pk)
        rated_movie_list = movie_object.ratedmovie.all()
        total_voters = rated_movie_list.count()
        if total_voters != 0:
            filtered_rating = rated_movie_list.filter(rating=rating).count()
            rating_percentage = (filtered_rating / total_voters) * 100
            return rating_percentage
        else:
            rating_percentage = 0
            return rating_percentage

    @property
    def total_voters(self):
        movie_object = Movie.objects.get(pk=self.pk)
        rated_movie_list = movie_object.ratedmovie.all()
        total_voters = rated_movie_list.count()
        return total_voters

    @property
    def one_star_percentage(self):
        return self.star_percentage(rating=1)

    @property
    def two_star_percentage(self):
        return self.star_percentage(rating=2)

    @property
    def three_star_percentage(self):
        return self.star_percentage(rating=3)

    @property
    def four_star_percentage(self):
        return self.star_percentage(rating=4)

    @property
    def five_star_percentage(self):
        return self.star_percentage(rating=5)

    @property
    def get_rating(self):
        movie_object = Movie.objects.get(pk=self.pk)
        rated_movie_list = movie_object.ratedmovie.all()
        total_voters = rated_movie_list.count()
        total_movie_rating = 0
        if total_voters != 0:
            for rating in range(1, 6):
                total_movie_rating += (rated_movie_list.filter(rating=rating).count()) * rating
            movie_rating = total_movie_rating / total_voters
            return movie_rating
        else:
            movie_rating = 0
            return movie_rating




class Tag(models.Model):
    movie = models.ManyToManyField(Movie, related_name='movie')
    tag_name = models.CharField(max_length=30)

    def __str__(self):
        return self.tag_name


class UserProfile(models.Model):
    owner = models.OneToOneField(User, on_delete=models.CASCADE)
    phone_number = models.BigIntegerField(unique=True, default=0)
    gender = models.CharField(max_length=6, choices=(('Male', 'Male'), ('Female', 'Female'), ('Others', 'Others')))
    location = models.CharField(max_length=30)

    def __str__(self):
        return self.owner.username

class Language(models.Model):
    name = models.CharField(max_length=20)

    def __str__(self):
        return self.name


class UserProfile(models.Model):
    owner = models.OneToOneField(User, on_delete=models.CASCADE)
    phone_number = models.BigIntegerField(unique=True, default=0)
    gender = models.CharField(
        max_length=6, choices=(('Male', 'Male'), ('Female', 'Female'), ('Others', 'Others')))
    location = models.CharField(max_length=30)
    is_rated = models.BooleanField(default=False)

    def __str__(self):
        return self.owner.username


class MovieRating(models.Model):
    movie = models.ForeignKey(Movie, related_name='ratedmovie', on_delete=models.CASCADE)
    user = models.ForeignKey(User, related_name='rateduser', on_delete=models.CASCADE)
    rating = models.IntegerField(default=0)

    def __str__(self):
        return self.movie.name + self.user.username

Qfxcinema/forms.py
from django import forms
from .models import UserProfile
from django.contrib.auth.models import User


class UserForm(forms.ModelForm):

	error_message = {'password_mismatch': 'Two password field didnt match'}
	password1 = forms.CharField(label="Password", widget=forms.PasswordInput)
	password2 = forms.CharField(
		label="Password Confirmation", widget=forms.PasswordInput,
		help_text="Enter the same passowrd as above")

	class Meta:
		model = User
		fields = ('username', 'first_name', 'last_name', 'email')

	def clean_password2(self):
		password1 = self.cleaned_data.get("Password1")
		password2 = self.cleaned_data.get("Password2")
		if password1 and password2 and password1 != password2:
			raise forms.ValidationError(
				self.error_message['password_mismatch'], code='password_mismatch')
		return password2


class ProfileForm(forms.ModelForm):
	class Meta:
		model = UserProfile
		fields = ('gender', 'phone_number', 'location')


class UserUpdateForm(forms.ModelForm):

	username = forms.CharField(widget=forms.TextInput(attrs={'readonly': 'readonly'}))

	class Meta:
		model = User
		fields = ('username', 'first_name', 'last_name', 'email')


class PasswordChangeForm(forms.ModelForm):
	password1 = forms.CharField(label="Password", widget=forms.PasswordInput)
	password2 = forms.CharField(
		label="Password Confirmation",
		widget=forms.PasswordInput, help_text='Enter the same Password as above')
	error_message = {'password_mismatch': 'Two Passowrd Field Didnt match'}

	class Meta:
		model = User
		fields = ('username', )

	def clean_password(self):
		Password1 = self.cleaned_data['password1']
		Password2 = self.cleaned_data['password2']
		if Password1 and Password2 and Password1 != Password2:
			raise forms.ValidationError(
				self.error_message['password_mismatch'], code='password_mismatch')
			return Password2

Qfxcinema/api/views.py
from .serializers import MovieSerializer, GenreSerializer
from Qfxcinema.models import Movie, Genre
from rest_framework import viewsets


class GenreViewSet(viewsets.ModelViewSet):
    queryset = Genre.objects.all()
    serializer_class = GenreSerializer


class MovieViewSet(viewsets.ModelViewSet):
    queryset = Movie.objects.all()
    serializer_class = MovieSerializer

Qfxcinema/views.py
from django.shortcuts import render

# Create your views here.

Qfxcinema/templates/base.html
{% load staticfiles %}
<html>
<head>

    <title>

        {% block title %} Base {% endblock %}
    </title>
    <script src="http://code.jquery.com/jquery-1.10.1.min.js"></script>
    <!-- Latest compiled and minified CSS -->
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css" integrity="sha384-BVYiiSIFeK1dGmJRAkycuHAHRg32OmUcww7on3RYdg4Va+PmSTsz/K68vbdEjh4u" crossorigin="anonymous">

    <!-- Optional theme -->
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap-theme.min.css" integrity="sha384-rHyoN1iRsVXV4nD0JutlnGaslCJuC7uwjduW9SVrLvRYooPp2bWYgmgJQIXwl/Sp" crossorigin="anonymous">



    <link rel="stylesheet" type="text/css" href="https://maxcdn.bootstrapcdn.com/font-awesome/4.7.0/css/font-awesome.min.css">

    <!-- Latest compiled and minified JavaScript -->
    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/js/bootstrap.min.js" integrity="sha384-Tc5IQib027qvyjSMfHjOMaLkfuWVxZxUPnCJA7l2mCWNIpG9mGCD8wGNIcPD7Txa" crossorigin="anonymous"></script>

</head>
<body class="bg-danger">
<nav class="navbar navbar-inverse">
    <div class="container-fluid">
        <ul class="nav navbar-nav">
            <li class="active"><a href="{% url 'Qfxcinema:movie-list' %}">Home</a></li>
            <li><a href="{% url 'Qfxcinema:movie-create' %}">Create Movie</a></li>
            <li><a href="{% url 'Qfxcinema:genre-create' %}">Genre</a></li>
            <li><a href="{% url 'Qfxcinema:tag-create' %}">Tag</a></li>
            <li><a href="{% url 'Qfxcinema:language-create' %}">Language</a></li>



        </ul>

        <div class=" col-sm-6 col-md-6">
            <form class="navbar-form text-right" role="search" method="get" action="{% url 'Qfxcinema:movie_search' %}">
                <div class="input-group">
                    <input type="text" class="form-control" placeholder="Search" name="name">
                    <div class="input-group-btn">
                        <button class="btn btn-default" type="submit"><i class="glyphicon glyphicon-search"></i></button>
                    </div>
                </div>
            </form>
        </div>
        <ul class="nav navbar-nav navbar-right">

            <li><a href="{% url 'Qfxcinema:user_register' %}"><span class="glyphicon glyphicon-user"></span>Register</a></li>

            <li><a href="{% url 'Qfxcinema:login' %}"><span class="glyphicon glyphicon-log-in"></span> Login</a></li>
            <li><a href="{% url 'Qfxcinema:logout' %}"><span class="glyphicon glyphicon-log-out"></span> LogOut</a></li>
        </ul>
    </div>
</nav>




{% block body %}
{% endblock %}

</body>
</html>