Qfxcinema/api/urls.py
from django.urls import path, include
from .views import MovieViewSet, GenreViewSet
from rest_framework.routers import DefaultRouter


router  = DefaultRouter()
router.register(r'genres', GenreViewSet)
router.register(r'movies', MovieViewSet)


urlpatterns = [

	path('', include(router.urls)),
	path('api-auth', include('rest_framework.urls', namespace='rest_framework'))
]

Qfxcinema/urls.py
from django.urls import path, include
from .movie_views import MovieListView, MovieDetailView, MovieCreateView, MovieUpdateView, movie_search, rating_create, MovieDeleteView
from .genre_views import GenreListView, GenreDetailView, GenreCreateView, GenreUpdateView, genre_search
from Qfxcinema.user_views import UserRegisterView, UserProfileView
from .tag_views import TagListView, TagDetailView, TagCreateView, TagUpdateView, tag_search
from .language_views import LanguageCreateView, LanguageListView, LanguageUpdateView, LanguageDeleteView
from django.contrib.auth.views import LoginView, LogoutView
from django.views.generic import TemplateView

app_name = 'Qfxcinema'

urlpatterns = [

    path('', MovieListView.as_view(), name='movie-list'),
    path('search/', movie_search, name='movie_search'),
    path('create/', MovieCreateView.as_view(), name='movie-create'),
    path('<int:pk>/', MovieDetailView.as_view(), name='movie-detail'),
    path('<int:pk>/update/', MovieUpdateView.as_view(), name='movie-update'),
    path('<int:pk>/delete/', MovieDeleteView.as_view(), name='movie-delete'),

    path('', GenreListView.as_view(), name='genre-list'),
    path('genre/search/', genre_search, name='genre_search'),
    path('create/genre/', GenreCreateView.as_view(), name='genre-create'),
    path('genre/<int:pk>/', GenreDetailView.as_view(), name='genre-detail'),
    path('genre/<int:pk>/update/', GenreUpdateView.as_view(), name='genre-update'),

    path('', TagListView.as_view(), name='tag-list'),
    path('search/', genre_search, name='tag_search'),
    path('create/tag/', TagCreateView.as_view(), name='tag-create'),
    path('<int:pk>/', TagDetailView.as_view(), name='tag-detail'),
    path('tag/<int:pk>/update/', TagUpdateView.as_view(), name='tag-update'),

    path('user/register/', UserRegisterView.as_view(), name='user_register'),
    path('user/profile/', UserProfileView.as_view(), name='user-detail'),
    path('user/login/', LoginView.as_view(template_name='user/login.html'), name='login'),
    path('user/logout/', LogoutView.as_view(next_page='/movie'), name='logout'),



    path('language/create/', LanguageCreateView.as_view(), name='language-create'),
    path('language/list/', LanguageListView.as_view(), name='language-list'),
    path('language/<int:pk>/update/', LanguageUpdateView.as_view(), name='language-update'),
    path('language/<int:pk>/delete/', LanguageDeleteView.as_view(), name='language-delete'),

    path('rating/create/', rating_create, name='movie_rating')
]

cinemasite/urls.py
from django.contrib import admin
from django.urls import path, include
from . import settings
from django.conf.urls.static import static


urlpatterns = [
    path('admin/', admin.site.urls),
    path('movie/', include('Qfxcinema.urls')),
    path('api/', include('Qfxcinema.api.urls')),


]



if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

Qfxcinema/models.py
from django.db import models
from django.urls import reverse
from django.utils.text import slugify
from django.contrib.auth.models import User
from django.dispatch import receiver
from django.db.models.signals import post_save


class Genre(models.Model):
    name = models.CharField(max_length=30)


    def __str__(self):
        return self.name


class Movie(models.Model):
    name = models.CharField(max_length=100, blank=False, null=False)
    genre = models.ForeignKey(Genre, related_name='genre', on_delete=models.DO_NOTHING)
    release_date = models.DateField(auto_now=False, auto_now_add=False)
    run_time = models.CharField(max_length=15)
    cast = models.TextField()
    slug = models.SlugField(unique=True, blank=True, max_length=50, null=True)
    poster = models.ImageField(upload_to='posters', null=True)
    youtube_link = models.TextField(blank=True, null=True)

    def __str__(self):
        return self.name

    def Moviesave(self):
        self.slug = slugify(self.name)
        super(Movie).save(Movie)

    def get_absolute_url(self):
        return reverse('Qfxcinema:movie-list')


    @property
    def get_user_rating(self):
        movie_object = Movie.objects.get(pk=self.pk)
        user_ratings_dict = movie_object.ratedmovie.all().values('user__username', 'rating')
        user_ratings_list = []
        user_ratings = ''
        for item in user_ratings_dict:
            user_ratings += '<li>' + item['user__username'] + ' has give rating of ' + \
                            str(item['rating']) + '</li>'
            user_ratings_list = user_ratings
        return user_ratings_list

    def star_percentage(self, rating):
        movie_object = Movie.objects.get(pk=self.pk)
        rated_movie_list = movie_object.ratedmovie.all()
        total_voters = rated_movie_list.count()
        if total_voters != 0:
            filtered_rating = rated_movie_list.filter(rating=rating).count()
            rating_percentage = (filtered_rating / total_voters) * 100
            return rating_percentage
        else:
            rating_percentage = 0
            return rating_percentage

    @property
    def total_voters(self):
        movie_object = Movie.objects.get(pk=self.pk)
        rated_movie_list = movie_object.ratedmovie.all()
        total_voters = rated_movie_list.count()
        return total_voters

    @property
    def one_star_percentage(self):
        return self.star_percentage(rating=1)

    @property
    def two_star_percentage(self):
        return self.star_percentage(rating=2)

    @property
    def three_star_percentage(self):
        return self.star_percentage(rating=3)

    @property
    def four_star_percentage(self):
        return self.star_percentage(rating=4)

    @property
    def five_star_percentage(self):
        return self.star_percentage(rating=5)

    @property
    def get_rating(self):
        movie_object = Movie.objects.get(pk=self.pk)
        rated_movie_list = movie_object.ratedmovie.all()
        total_voters = rated_movie_list.count()
        total_movie_rating = 0
        if total_voters != 0:
            for rating in range(1, 6):
                total_movie_rating += (rated_movie_list.filter(rating=rating).count()) * rating
            movie_rating = total_movie_rating / total_voters
            return movie_rating
        else:
            movie_rating = 0
            return movie_rating




class Tag(models.Model):
    movie = models.ManyToManyField(Movie, related_name='movie')
    tag_name = models.CharField(max_length=30)

    def __str__(self):
        return self.tag_name


class UserProfile(models.Model):
    owner = models.OneToOneField(User, on_delete=models.CASCADE)
    phone_number = models.BigIntegerField(unique=True, default=0)
    gender = models.CharField(max_length=6, choices=(('Male', 'Male'), ('Female', 'Female'), ('Others', 'Others')))
    location = models.CharField(max_length=30)

    def __str__(self):
        return self.owner.username

class Language(models.Model):
    name = models.CharField(max_length=20)

    def __str__(self):
        return self.name


class UserProfile(models.Model):
    owner = models.OneToOneField(User, on_delete=models.CASCADE)
    phone_number = models.BigIntegerField(unique=True, default=0)
    gender = models.CharField(
        max_length=6, choices=(('Male', 'Male'), ('Female', 'Female'), ('Others', 'Others')))
    location = models.CharField(max_length=30)
    is_rated = models.BooleanField(default=False)

    def __str__(self):
        return self.owner.username


class MovieRating(models.Model):
    movie = models.ForeignKey(Movie, related_name='ratedmovie', on_delete=models.CASCADE)
    user = models.ForeignKey(User, related_name='rateduser', on_delete=models.CASCADE)
    rating = models.IntegerField(default=0)

    def __str__(self):
        return self.movie.name + self.user.username

Qfxcinema/forms.py
from django import forms
from .models import UserProfile
from django.contrib.auth.models import User


class UserForm(forms.ModelForm):

	error_message = {'password_mismatch': 'Two password field didnt match'}
	password1 = forms.CharField(label="Password", widget=forms.PasswordInput)
	password2 = forms.CharField(
		label="Password Confirmation", widget=forms.PasswordInput,
		help_text="Enter the same passowrd as above")

	class Meta:
		model = User
		fields = ('username', 'first_name', 'last_name', 'email')

	def clean_password2(self):
		password1 = self.cleaned_data.get("Password1")
		password2 = self.cleaned_data.get("Password2")
		if password1 and password2 and password1 != password2:
			raise forms.ValidationError(
				self.error_message['password_mismatch'], code='password_mismatch')
		return password2


class ProfileForm(forms.ModelForm):
	class Meta:
		model = UserProfile
		fields = ('gender', 'phone_number', 'location')


class UserUpdateForm(forms.ModelForm):

	username = forms.CharField(widget=forms.TextInput(attrs={'readonly': 'readonly'}))

	class Meta:
		model = User
		fields = ('username', 'first_name', 'last_name', 'email')


class PasswordChangeForm(forms.ModelForm):
	password1 = forms.CharField(label="Password", widget=forms.PasswordInput)
	password2 = forms.CharField(
		label="Password Confirmation",
		widget=forms.PasswordInput, help_text='Enter the same Password as above')
	error_message = {'password_mismatch': 'Two Passowrd Field Didnt match'}

	class Meta:
		model = User
		fields = ('username', )

	def clean_password(self):
		Password1 = self.cleaned_data['password1']
		Password2 = self.cleaned_data['password2']
		if Password1 and Password2 and Password1 != Password2:
			raise forms.ValidationError(
				self.error_message['password_mismatch'], code='password_mismatch')
			return Password2

Qfxcinema/api/views.py
from .serializers import MovieSerializer, GenreSerializer
from Qfxcinema.models import Movie, Genre
from rest_framework import viewsets


class GenreViewSet(viewsets.ModelViewSet):
    queryset = Genre.objects.all()
    serializer_class = GenreSerializer


class MovieViewSet(viewsets.ModelViewSet):
    queryset = Movie.objects.all()
    serializer_class = MovieSerializer

Qfxcinema/views.py
from django.shortcuts import render

# Create your views here.

Qfxcinema/templates/Qfxcinema/create.html
{% extends 'base.html' %}

{% block title %}
Create Movies
{% endblock %}

{% block body %}

<div class="container">
	<h1>{{ Create_Movie }} {{ Update_Movie }}</h1>

	<form method="Post" enctype="multipart/form-data">
		{% csrf_token %}

		{{ form.as_p }} <br>
		<button type="submit" class="btn btn-info btn-lg">{{ Create }} {{ Update }}</button>

	</form>
</div>


{% endblock%}

Qfxcinema/templates/Qfxcinema/detail.html
{% extends 'base.html' %}

{% block title %}
Movie Detail
{% endblock %}

{% block body %}
<div class="container form-group">

	<form class="from-group">

		<span class="col-sm-1"></span>
		<div class="container" height="400" width="400">{{ Movie.youtube_link|safe }}</div>

		<br><br>
		<br><br>

		<span class="col-xs-1"></span>
		<img src="{{ Movie.poster.url }}" alt="posters" width="400" height="550" class="img-rounded img-fill">

		<span class="col-xs-5">

			<div class="container" height="auto">
				<div class="row">
					<div class="col-xs-6 col-sm-4">
						<div class="well well-sm">
							<div class="row">
								<div class="col-xs-12 col-md-6 text-center">
									<h1 class="rating-num">
									{{ Movie.get_rating|floatformat }}</h1>

									<div>
										<span class="glyphicon glyphicon-user"></span>{{ Movie.total_voters }} total
									</div>
								</div>
								<div class="col-xs-12 col-md-6">
									<div class="row rating-desc">
										<div class="col-xs-3 col-md-3 text-right">
											<span class="glyphicon glyphicon-star"></span>5
										</div>
										<div class="col-xs-8 col-md-9">
											<div class="progress progress-striped">
												<div class="progress-bar progress-bar-success" role="progressbar" aria-valuenow="20"
													 aria-valuemin="0" aria-valuemax="100" style="width: {{Movie.five_star_percentage}}%">
												<span class="sr-only">{{Movie.five_star_percentage|floatformat:"0"}}%</span>
											</div>
										</div>
									</div>
										<!-- end 5 -->
									<div class="col-xs-3 col-md-3 text-right">
										<span class="glyphicon glyphicon-star"></span>4
									</div>
									<div class="col-xs-8 col-md-9">
										<div class="progress">
											<div class="progress-bar progress-bar-success" role="progressbar" aria-valuenow="20"
												 aria-valuemin="0" aria-valuemax="100" style="width: {{Movie.four_star_percentage}}%">
											<span class="sr-only">{{Movie.four_star_percentage|floatformat:"0"}}</span>
										</div>
									</div>
								</div>
										<!-- end 4 -->
								<div class="col-xs-3 col-md-3 text-right">
									<span class="glyphicon glyphicon-star"></span>3
								</div>
								<div class="col-xs-8 col-md-9">
									<div class="progress">
										<div class="progress-bar progress-bar-info" role="progressbar" aria-valuenow="20"
											 aria-valuemin="0" aria-valuemax="100" style="width: {{Movie.three_star_percentage}}%">
										<span class="sr-only">{{Movie.three_star_percentage|floatformat:"0"}}%</span>
									</div>
								</div>
							</div>
										<!-- end 3 -->
							<div class="col-xs-3 col-md-3 text-right">
								<span class="glyphicon glyphicon-star"></span>2
							</div>
							<div class="col-xs-8 col-md-9">
								<div class="progress">
									<div class="progress-bar progress-bar-warning" role="progressbar" aria-valuenow="20"
										 aria-valuemin="0" aria-valuemax="100" style="width: {{Movie.two_star_percentage}}%">
									<span class="sr-only">{{Movie.two_star_percentage|floatformat:"0"}}%</span>
								</div>
							</div>
						</div>
										<!-- end 2 -->
						<div class="col-xs-3 col-md-3 text-right">
							<span class="glyphicon glyphicon-star"></span>1
						</div>
						<div class="col-xs-8 col-md-9">
							<div class="progress">
								<div class="progress-bar progress-bar-danger" role="progressbar" aria-valuenow="80"
									 aria-valuemin="0" aria-valuemax="100" style="width: {{Movie.one_star_percentage}}%">
								<span class="sr-only">{{Movie.one_star_percentage|floatformat:"0"}}%</span>
							</div>
						</div>
					</div>
										<!-- end 1 -->
				</div>
									<!-- end row -->
			</div>
		</div>

	</span>

</div>



</form>
<br>
<br>
<div class="text-center ">
	<h3>
		Movie Name : {{ Movie.name }}<br>
		Genre      : {{ Movie.genre }}<br>
		Cast       : {{ Movie.name }}<br>
		Release Date : {{ Movie.release_date }}<br>
		Run Time   :  {{ Movie.run_time }}

	</h3>




	<br>
	<br>
	{% if user.is_superuser %}


	<a href="{% url 'Qfxcinema:movie-update' Movie.pk %}" class="btn btn-info">Update This Movie</a>

	<a href="{% url 'Qfxcinema:movie-delete' Movie.pk %}" class="btn btn-danger">Delete This Movie</a>







	{% endif %}

</div>
<br>
<br>
<div class="container">
	<br>
	<br>
	<br>
	<br>
	<div>

		<span class="col-sm-5"> </span>

		<span class="col-md-6">
				<br>
					<strong class="pull-center"><h1 id="before_click">Click TO Rate !!!</h1>
						<h1 id="after_click">You Have Rated This Movie</h1>
						<form method="Post">{% csrf_token %}
							<h1>
								<input type="hidden" value="{{ Movie.pk }}" id="pk">
								<input type="hidden" value="{{ request.user.username }}" id="user">
								<input type="hidden" value="{{ Movie.name }}" id="movieName">
								<input type="hidden" value="{{ rating }}" id="userRating">
								<fieldset class="rating">
									<input type="radio" id="star5" name="rating" value="5" /><label class = "full" for="star5" title="Awesome - 5 stars"></label>

									<input type="radio" id="star4" name="rating" value="4" /><label class = "full" for="star4" title="Pretty good - 4 stars"></label>

									<input type="radio" id="star3" name="rating" value="3" /><label class = "full" for="star3" title="Meh - 3 stars"></label>

									<input type="radio" id="star2" name="rating" value="2" /><label class = "full" for="star2" title="Kinda bad - 2 stars"></label>

									<input type="radio" id="star1" name="rating" value="1" /><label class = "full" for="star1" title="Sucks big time - 1 star"></label>

								</fieldset>
							</h1>

						</form>



			</strong>
			</span>
	</div>
</div>







<span class="col-sm-3"></span>		<!-- http://www.jquery2dotnet.com/ -->

<br><br>
{% if user.is_superuser %}
<p>
	This movie is rated by following users:
<ol>
	{{ Movie.get_user_rating | safe }}

</ol>

</p>
{% endif %}

















<style type="text/css">
body{ margin-top:20px;}
.glyphicon { margin-right:5px;}
.rating .glyphicon {font-size: 22px;}
.rating-num { margin-top:0px;font-size: 54px; }
.progress { margin-bottom: 5px;}
.progress-bar { text-align: left; }
.rating-desc .col-md-3 {padding-right: 0px;}
.sr-only { margin-left: 5px;overflow: visible;clip: auto; },
fieldset, label { margin: 0; padding: 0; }
body{ margin: 20px; }
h1 { font-size: 1.5em; margin: 10px; }
/****** Style Star Rating Widget *****/
.rating {
	border: none;
	float: left;
}
.rating > input { display: none; }
.rating > label:before {
	margin: 5px;
	font-size: 1.25em;
	font-family: FontAwesome;
	display: inline-block;
	content: "\f005";
}
.rating > .half:before {
	content: "\f089";
	position: absolute;
}
.rating > label {
	color: #ffb3b3;
	float: right;
}
/***** CSS Magic to Highlight Stars on Hover *****/
.rating > input:checked ~ label, /* show gold star when clicked */
.rating:not(:checked) > label:hover, /* hover current star */
.rating:not(:checked) > label:hover ~ label { color: #660000;  } /* hover previous stars in list */
.rating > input:checked + label:hover, /* hover current star when changing rating */
.rating > input:checked ~ label:hover,
.rating > label:hover ~ input:checked ~ label, /* lighten current selection */
.rating > input:checked ~ label:hover ~ label { color: 	#ffb3b3;  }
</style>



<script type="text/javascript">
	$("#after_click").hide();
	$(document).on("ready", function(){
		if($("#userRating").val() !== ""){
			rating = $("#userRating").val();
			rate = Number(rating);
			for(i=1; i<=rate; i++){
				var star = "#star";
				var star_rate = String(i);
				var star_id = star.concat(star_rate);
				$(star_id).prop("checked", true)
			}
			$(":radio").prop("disabled", true);
			$("#before_click").hide();
			$("#after_click").show();
		}
	})
	$(document).one('click', ":radio", function(e){
		e.preventDefault;
		$.ajax({
			type : 'POST',
			url : '{% url 'Qfxcinema:movie_rating' %}',
			data : {
				rating : $(this).val(),
				pk : $("#pk").val(),
				user : $("#user").val(),
				movie : $("#movieName").val(),
				csrfmiddlewaretoken: '{{ csrf_token }}',
			},
			success :function(data){

				$("#before_click").hide();
				$("#after_click").show();
				var rate = Number(data.rating)
				for (var i = 1; i <= rate; i++) {
					var star = "#star";
					var star_rate = String(i);
					var star_id = star.concat(star_rate);
					$(star_id).prop("checked", true)

				}
				$(":radio").prop("disabled", true)
				/*$("#star1").prop("checked", true);*/
			}
		});
	})
</script>


{% endblock%}

Qfxcinema/templates/Qfxcinema/home.html
{% extends 'base.html' %}

{% block title %}
Home
{% endblock %}

{% block body %}

<div class="container">

    <div class="page-header">
        <h1 class="my-4 text-center text-lg-left text-danger">Now Showing Movies</h1>

    </div>

    <br>

    <div class="row">

        {% for now_showing_movie in now_showing_movies %}



        <div class="col-lg-4">
            <a href="{% url 'Qfxcinema:movie-detail' now_showing_movie.pk %}" class="d-block mb-4 h-100">
                <img class="img-rounded img-responsive" src="{{ now_showing_movie.poster.url }}" alt="" width="300" height="350">

            </a>
            <strong><h2 class="text-center"> {{ now_showing_movie }}</h2></strong>
        </div>


        {% endfor %}
    </div>
    <div class="container">
        <br>
        <br>
        <div class="page-header">

            <h1 class="my-4 text-center text-lg-left text-danger">Upcoming Movies</h1>

        </div>
        <div class="row">

            {% for Movie in Movies %}



            <div class="col-lg-4">
                <a href="{% url 'Qfxcinema:movie-detail' Movie.pk %}" class="d-block mb-4 h-100">
                    <img class="img-responsive img-rounded" src="{{ Movie.poster.url }}" alt=""width="300" height="350">

                </a>
                <strong><h2 class="text-center"> {{ Movie }}</h2></strong>

            </div>


            {% endfor %}
        </div>

    </div>

    <style type="text/css">

img {
    width: 500px; /* You can set the dimensions to whatever you want */
    height: 300px;
    object-fit: cover;
}
</style>

    {% endblock%}